:Author: khaledallen
:Email: {AuthorEmail}
:Date: 15/02/2021
:Revision: version#
:License: Public Domain

= Project: Sunrise Simulation Lamp

Gets the next upcoming sunrise from a sunrise API, then triggers an Adafruit Neopixel to begin a 
sunrise simulation sequence, going from dim and deep red to bright and white. Includes the STL for
a 3D printed bulb enclosure and mounting plate for the Neopixel (using translucent PETG).

== Step 1: Installation
Please describe the steps to install this project.

1. Adjust your desired sunrise sequence using the file `sunrise.ino`.
2. Once you have something you like, copy it into `sunrise-on-time.ino`.

== Step 2: Assemble the circuit

The sketch expects the DATA IN for the Neopixel to be connected to pin 6 on the Arduino.
The clock needs to be connected to corresponding pins on the Arduino (SDA to SDA, SCL to SCL).

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sunrise.ino         => just the sunrise sequence for testing
  ├── sunrise-on-time.ino => the code for connecting to Wifi, getting the time of the sunrise, comparing it to the RTC, and triggering the sunrise
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a Creative Commons License.

=== Contributing
To contribute to this project please contact khaledallen https://id.arduino.cc/khaledallen

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | Real time clock   | -   | 1
| L1 | 12-LED RGBW Adafruit Neopixel Ring        | -   | 1
| A1 | Arduino MKR1000   | -    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
